spring:
  application:
    name: revo-config-server
  cloud:
    config:
      server:
        git:
          uri:
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
